# Categorizing Records in Pandas DataFrames

## 1. Import Libraries and Dependencies

In [20]:
# import dependencies
import pandas as pd
from pathlib import Path
%matplotlib inline

## 2. Set the File Path to the CSV using Pathlib

In [21]:
# Use the Pathlib libary to set the path to the CSV
csvpath = Path("../Resources/cleaned_people_data.csv")

## 3. Import the CSV into Pandas DataFrame

In [22]:
# Use the file path to read the CSV into a DataFrame and display a few rows
people_df = pd.read_csv(csvpath, index_col="Person_ID")
people_df.head()

,Last_Name,First_Name,Gender,University,Occupation,Salary,Email,Age
Person_ID,,,,,,,,
1,Lenormand,Keriann,Female,Aurora University,Nurse Practicioner,58135.0,klenormand0@businessinsider.com,27
2,Rupke,Huntley,Male,Osaka University of Economics,Project Manager,96053.0,hrupke1@reuters.com,22
3,Dalgarnowch,Gorden,Male,Ludong University,Environmental Tech,59196.0,gdalgarnowch2@microsoft.com,40
4,Unnamed,Cullie,Male,Université des Sciences et de la Technologie d...,Legal Assistant,88493.0,cputten3@nymag.com,62
5,Strangman,Ariel,Female,Boise State University,Project Manager,89073.0,astrangman4@bravesites.com,47

## 4. Create Bins for Total Ranking

In [23]:
# Create the variable bins to define our bounds for when we cut the dataframe.
bins = [0, 30000, 70000, 100000, 200000]
bin_names = ['Low', 'Moderate', 'Above Average', 'High']

# Create names for the bins

## 5. Label Records According to the Corresponding Bin

In [24]:
# Add a column named "Salary Level" to people_df and slice the data into the bins
people_df["Salary Level"] = pd.cut(people_df["Salary"], bins, labels= bin_names)
people_df.tail(30)

,Last_Name,First_Name,Gender,University,Occupation,Salary,Email,Age,Salary Level
Person_ID,,,,,,,,,
971,Perchard,Ennis,Male,University of Exeter,Accounting Assistant I,109716.0,eperchardqy@storify.com,64,High
972,Attfield,Sigrid,Female,Universidad de La Salle,Senior Quality Engineer,93769.0,sattfieldqz@nationalgeographic.com,42,Above Average
973,Spurdle,Kathi,Female,United States Sports Academy,VP Marketing,56669.0,kspurdler0@ucla.edu,48,Moderate
974,Haspineall,Antonio,Male,Lansbridge University,Legal Assistant,71608.0,ahaspineallr1@simplemachines.org,33,Above Average
975,Shoveller,Bernadina,Female,Midwestern State University,Assistant Manager,63355.0,bshovellerr2@ca.gov,33,Moderate
976,Pickett,Nanete,Female,Ecole Nationale Supérieure de Physique de Gren...,Human Resources Manager,108835.0,npickettr3@businesswire.com,61,High
977,Lethbrig,Hastie,Male,Ecole Polytechnique,Electrical Engineer,73842.0,hlethbrigr4@europa.eu,32,Above Average
978,McPhillimey,Danice,Female,Université d'Artois,Automation Specialist II,71578.0,dmcphillimeyr5@flickr.com,60,Above Average
979,Yurchenko,Kale,Male,Southeast Missouri State University,Biostatistician IV,54576.0,kyurchenkor6@netscape.com,54,Moderate
980,Eykel,Dillon,Male,Shorter College,Pharmacist,110623.0,deykelr7@independent.co.uk,58,High
981,Tarbox,Alley,Male,University of Alaska (System),Speech Pathologist,91118.0,atarboxr8@comcast.net,28,Above Average
982,Cocksedge,Nydia,Female,University of Wroclaw,Quality Engineer,63085.0,ncocksedger9@goo.gl,38,Moderate
983,Boutellier,Dayna,Female,Ummah University,Software Engineer I,70141.0,dboutellierra@tumblr.com,22,Above Average
984,Maharey,Angie,Female,Utsunomiya University,Accountant I,65560.0,amahareyrb@w3.org,61,Moderate
985,Strongitharm,Felice,Male,University of Engineering and Technology Peshawar,Actuary,60366.0,fstrongitharmrc@pen.io,43,Moderate
986,Grint,Humbert,Male,National Technical University (Kharkiv Polytec...,Financial Analyst,114068.0,hgrintrd@google.com.br,64,High
987,Morratt,Kaye,Female,Shaheed Zulifkar Ali Bhutto Institute of Scien...,Senior Sales Associate,82362.0,kmorrattre@youku.com,53,Above Average
988,Karolczyk,Jillie,Female,Providence College,Dental Hygienist,52966.0,jkarolczykrf@unblog.fr,26,Moderate
989,Waker,Estrellita,Female,New England College,Database Administrator I,80118.0,ewakerrg@angelfire.com,59,Above Average
990,Unnamed,Urson,Male,Wilberforce University,Librarian,79603.0,uenrdigorh@gmpg.org,48,Above Average
991,Hampshire,Julian,Male,Johnson & Wales University,Chemical Engineer,79024.0,jhampshireri@disqus.com,26,Above Average
992,Glossop,Davine,Female,Université René Descartes (Paris V),VP Quality Control,50599.0,dglossoprj@goodreads.com,47,Moderate
993,Rugg,Dorothea,Female,Universidad Politécnica de El Salvador,VP Marketing,114586.0,druggrk@miitbeian.gov.cn,51,High
994,Griffitts,Damaris,Female,The College of Wooster,Senior Editor,113339.0,dgriffittsrl@mapquest.com,42,High
995,Jeacop,Iggy,Male,University of Greenwich,Sales Associate,82726.0,ijeacoprm@4shared.com,22,Above Average
996,Crumpton,Meta,Female,ECAM - Institut Supérieur Industriel,Registered Nurse,57060.0,mcrumptonrn@qq.com,52,Moderate
997,Gilford,Gunar,Male,Smolny University,Marketing Manager,76109.0,ggilfordro@yandex.ru,32,Above Average
998,Gurling,Lucretia,Female,Institut Teknologi Telkom,Software Engineer III,92115.0,lgurlingrp@de.vu,48,Above Average
999,Yang,Andrew,Male,Rutgers University School of Business,Curriculum Engineer,60000.0,ayang@codedrills.com,53,Moderate
999,Yang,Andrew,Male,Rutgers University School of Business,Curriculum Engineer,60000.0,ayang@codedrills.com,53,Moderate

In [25]:

people_df.dtypes

Last_Name         object
First_Name        object
Gender            object
University        object
Occupation        object
Salary           float64
Email             object
Age                int64
Salary Level    category
dtype: object